[template]
src = "opennms.properties.d/core.ipc.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/core.ipc.properties"
keys = [
    "/core/ipc/rpc/strategy",
    "/core/ipc/rpc/kafka/bootstrap/servers",
    "/core/ipc/rpc/kafka/ttl",
    "/core/ipc/rpc/kafka/max/buffer/size",
    "/core/ipc/aws/sqs/rpc/delay/seconds",
    "/core/ipc/aws/sqs/rpc/maximum/message/size",
    "/core/ipc/aws/sqs/rpc/message/retention/period",
    "/core/ipc/aws/sqs/rpc/receive/message/wait/time/seconds",
    "/core/ipc/aws/sqs/rpc/visibility/timeout",
    "/core/ipc/aws/sqs/rpc/policy",
    "/core/ipc/aws/sqs/rpc/redrive/policy",
    "/core/ipc/aws/sqs/rpc/kms/master/keyid",
    "/core/ipc/aws/sqs/rpc/kms/datakey/reuse/period/seconds",
    "/core/ipc/aws/sqs/rpc/fifo/queue",
    "/core/ipc/aws/sqs/rpc/content/based/deduplication",
    "/core/ipc/aws/sqs/aws/region",
    "/core/ipc/aws/sqs/aws/access/key/id",
    "/core/ipc/aws/sqs/aws/secret/access/key",
    "/core/ipc/sink/strategy",
    "/core/ipc/sink/initial/sleep/time",
    "/core/ipc/sink/kafka/bootstrap/servers",
    "/core/ipc/sink/kafka/group/id",
    "/core/ipc/aws/sqs/sink/delay/seconds",
    "/core/ipc/aws/sqs/sink/maximum/message/size",
    "/core/ipc/aws/sqs/sink/message/retention/period",
    "/core/ipc/aws/sqs/sink/receive/message/wait/time/seconds",
    "/core/ipc/aws/sqs/sink/visibility/timeout",
    "/core/ipc/aws/sqs/sink/policy",
    "/core/ipc/aws/sqs/sink/redrive/policy",
    "/core/ipc/aws/sqs/sink/kms/master/keyid",
    "/core/ipc/aws/sqs/sink/kms/datakey/reuse/period/seconds",
    "/core/ipc/aws/sqs/sink/fifo/queue",
    "/core/ipc/aws/sqs/sink/content/based/deduplication"
]
