[template]
src = "opennms.properties.d/heatmap.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/heatmap.properties"
keys = [
    "/heatmap/default/mode",
    "/heatmap/default/heatmap",
    "/heatmap/category/filter",
    "/heatmap/foreignsource/filter",
    "/heatmap/service/filter",
    "/heatmap/only/unacknowledged"
]
