[template]
src = "opennms.properties.d/icmp.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/icmp.properties"
keys = [
    "/icmp/pingerclass",
    "/icmp/requirev4",
    "/icmp/requirev6"
]
