[template]
src = "opennms.properties.d/icmp.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/icmp.properties"
keys = [
    "/icmp/pinger/class",
    "/icmp/require/v4",
    "/icmp/require/v6"
]
