[template]
src = "opennms.properties.d/ipc.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/ipc.properties"
keys = [
    "/rtc/event/proxy/host",
    "/rtc/event/proxy/port",
    "/rtc/event/proxy/timeout",
    "/rtc-client/http-post/base-url",
    "/rtc-client/http-post/username",
    "/rtc-client/http-post/password",
    "/map-client/http-post/url",
    "/map-client/http-post/username",
    "/map-client/http-post/password"
]
