[template]
src = "opennms.properties.d/jetty.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/jetty.properties"
keys = [
    "/jetty/port",
    "/jetty/ajpport",
    "/jetty/host",
    "/jetty/enable/request/logging",
    "/jetty/server/request/max/form/content/size",
    "/jetty/request/header/size",
    "/jetty/server/request/max/form/keys",
    "/jetty/https/port",
    "/jetty/https/host",
    "/jetty/https/keystore",
    "/jetty/https/keystore/password",
    "/jetty/https/keypassword",
    "/web/baseurl"
]
