[template]
src = "opennms.properties.d/misc.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/misc.properties"
keys = [
    "/distributed/layout/applications/vertically",
    "/opennms/bin/dir",
    "/java/awt/headless",
    "/dao/ipinterface/findby/servicetype",
    "/collectd/default/collection/agent/load/snmp/data/oninit",
    "/interface/node/cache/refresh/timer",
    "/osgi/bridge/rest/aliases",
    "/exclude/service/monitors/from/remote/poller",
    "/eventd/event/template/cache/size"
]
