[template]
src = "opennms.properties.d/reporting.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/reporting.properties"
keys = [
    "/report/template/dir",
    "/report/dir",
    "/report/logo",
    "/ksc/default/graphsperline"
]
