[template]
src = "opennms.properties.d/sms-gateway.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/sms-gateway.properties"
keys = [
    "/gnu/io/serialports",
    "/smslib/serial/polling",
]
