[template]
src = "opennms.properties.d/timeseries.properties.tpl"
dest = "/opt/opennms/etc/opennms.properties.d/timeseries.properties"
keys = [
    "/rrd/storeby/foreignsource",
    "/rrd/storeby/group",
    "/timeseries/strategy",
    "/rrd/binary",
    "/rrd/base/dir",
    "/rrd/strategy/class",
    "/rrd/interface/jar",
    "/rrd/library/jrrd2",
    "/evaluate/dump/stats/frequency",
    "/evaluate/dump/cache/frequency",
    "/newts/nan/on/counter/wrap",
    "/newts/config/hostname",
    "/newts/config/keyspace",
    "/newts/config/port",
    "/newts/config/username",
    "/newts/config/password",
    "/newts/config/read/consistency",
    "/newts/config/write/consistency",
    "/newts/config/writer/threads",
    "/newts/config/max/batchsize",
    "/newts/config/ring/buffer/size",
    "/newts/config/ttl",
    "/newts/config/resource/shard",
    "/newts/config/cache/strategy",
    "/newts/config/cache/max/entries",
    "/newts/config/cache/redis/hostname",
    "/newts/config/cache/redis/port",
    "/newts/config/cache/priming/disable",
    "/newts/config/cache/priming/blockms",
    "/newts/query/minimum/step",
    "/newts/query/heartbeat"
]
