[template]
src = "opennms-datasources.xml.tpl"
dest = "/opt/opennms/etc/opennms-datasources.xml"
keys = [
    "/database/connection/pool/factory",
    "/database/connection/pool/idle/timeout",
    "/database/connection/pool/login/timeout",
    "/database/connection/pool/min/pool",
    "/database/connection/pool/max/pool",
    "/database/connection/pool/max/size",
    "/database/name",
    "/database/user",
    "/database/password",
    "/postgres/host",
    "/postgres/port",
    "/postgres/user",
    "/postgres/password",
    
]
